Repository yalla-coop/scouts, pull requests merged in 2021-01, with the labels that each got.

#82 43 setup style system
  .eslintrc.js
  client/.storybook/preview.js
  client/.storybook/themeDecorator.js
  client/package.json
  client/src/App.js
  client/src/components/Typography/Typography.stories.js
  client/src/components/Typography/index.js
  client/src/helpers/setMargin.js
  client/src/index.css
  client/src/theme/global-style.js
  client/src/theme/index.js
  package-lock.json
  package.json
Labels: awaiting-review

#86 39 button component
  client/src/components/Button/Button.stories.js
  client/src/components/Button/button.css
  client/src/components/Button/index.js
  client/src/components/Button/style.js
Labels: awaiting-review

#85 40 create icon component
  client/src/components/Icon/Icon.stories.js
  client/src/components/Icon/icons/Backup.js
  client/src/components/Icon/icons/BrokenLamp.js
  client/src/components/Icon/icons/Calendar.js
  client/src/components/Icon/icons/Camera.js
  client/src/components/Icon/icons/Crown.js
  client/src/components/Icon/icons/Cup.js
  client/src/components/Icon/icons/Darts.js
  client/src/components/Icon/icons/Discussion.js
  client/src/components/Icon/icons/File.js
  client/src/components/Icon/icons/Flash.js
  client/src/components/Icon/icons/Notebook.js
  client/src/components/Icon/icons/Office.js
  client/src/components/Icon/icons/Planning.js
  client/src/components/Icon/icons/ShareMedia.js
  client/src/components/Icon/icons/TextFile.js
  client/src/components/Icon/index.js
Labels: awaiting-review

#87 47 circle diagram score
  client/.storybook/preview.js
  client/.storybook/theme-decorator.js
  client/src/components/CircleDiagram/CircleDiagram.stories.js
  client/src/components/CircleDiagram/index.js
  client/src/components/CircleDiagram/style.js
  client/src/components/Typography/index.js
  client/src/helpers/set-margin.js
Labels: awaiting-review

#90 Create all inputs
  client/.storybook/theme-decorator.js
  client/src/components/Icon/icons/Tick.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Inputs/Cards/index.js
  client/src/components/Inputs/Cards/style.js
  client/src/components/Inputs/Checkbox/index.js
  client/src/components/Inputs/Checkbox/style.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/Inputs.stories.js
  client/src/components/Inputs/Matrix/index.js
  client/src/components/Inputs/Options/index.js
  client/src/components/Inputs/Options/style.js
  client/src/components/Inputs/Radio/index.js
  client/src/components/Inputs/Radio/style.js
  client/src/components/Inputs/Slider/index.js
  client/src/components/Inputs/Slider/style.js
  client/src/components/Inputs/index.js
  client/src/components/Inputs/style.js
  client/src/index.css
  client/src/theme/global-style.js
  client/src/theme/index.js
Labels: awaiting-review

#88 45 question progress bar
  client/.storybook/theme-decorator.js
  client/src/components/ProgressBar/ProgressBar.stories.js
  client/src/components/ProgressBar/index.js
  client/src/components/ProgressBar/style.js
  client/src/theme/index.js
Labels: approved

#83 36 create layouts
  client/.storybook/theme-decorator.js
  client/src/App.js
  client/src/components/Icon/Icon.stories.js
  client/src/components/Icon/icons/ActivityComplete.js
  client/src/components/Icon/icons/Diamond.js
  client/src/components/Icon/icons/Notebook.js
  client/src/components/Icon/icons/Resources.js
  client/src/components/Icon/icons/SkillComplete.js
  client/src/components/Icon/icons/Success.js
  client/src/components/Icon/icons/ThankYou.js
  client/src/components/Icon/index.js
  client/src/components/Layout/General.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/Layout.stories.js
  client/src/components/Layout/Menu.js
  client/src/components/Layout/NavBar/index.js
  client/src/components/Layout/NavBar/style.js
  client/src/components/Layout/Notification.js
  client/src/components/Layout/Page.js
  client/src/components/Layout/SideBar/index.js
  client/src/components/Layout/WithBlocks.js
  client/src/components/Layout/WithoutHeader.js
  client/src/components/Layout/index.js
  client/src/components/Layout/style.js
  client/src/theme/index.js
Labels: requested-changes

#91 48 cards
  client/src/components/Button/style.js
  client/src/components/Card/CTA/index.js
  client/src/components/Card/Card.stories.js
  client/src/components/Card/DoingGreat/index.js
  client/src/components/Card/DoingGreat/style.js
  client/src/components/Card/HelpOut/index.js
  client/src/components/Card/Newsletter/index.js
  client/src/components/Card/Search/index.js
  client/src/components/Card/index.js
  client/src/components/Card/style.js
  client/src/components/Icon/Icon.stories.js
  client/src/components/Icon/icons/Cup.js
  client/src/components/Icon/icons/Help.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/style.js
  client/src/constants/dropdownData.js
  client/src/constants/index.js
  client/src/theme/index.js
Labels: awaiting-review

#92 46 activity header
  client/src/components/ActivityHeader/ActivityHeader.stories.js
  client/src/components/ActivityHeader/index.js
  client/src/components/ActivityHeader/style.js
  client/src/components/Icon/icons/Scouts.js
  client/src/components/Icon/index.js
  client/src/components/LevelIndicator/LevelIndicator.stories.js
  client/src/components/LevelIndicator/index.js
  client/src/components/LevelIndicator/style.js
  client/src/components/Typography/index.js
  client/src/theme/global-style.js
  client/src/theme/index.js
Labels: awaiting-review

#93 Add activities into init data > #49
  server/database/dummy-data/activities-skills.js
  server/database/dummy-data/activities.js
  server/database/dummy-data/initSkillsToActivitiesData.js
  server/database/dummy-data/users-completed-activities.js
Labels: awaiting-review

#94 50 landing
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Card/CTA/index.js
  client/src/components/Card/HelpOut/index.js
  client/src/components/Grid/style.js
  client/src/components/Icon/icons/Cup.js
  client/src/components/Layout/WithoutHeader.js
  client/src/components/Layout/style.js
  client/src/constants/nav-routes.js
  client/src/pages/Landing/index.js
  client/src/pages/index.js
  client/src/theme/index.js
Labels: awaiting-review

#96 Create digital test landing page > #53
  client/src/App.js
  client/src/components/BackLink/index.js
  client/src/components/BackLink/style.js
  client/src/components/Icon/icons/Clock.js
  client/src/components/Icon/index.js
  client/src/components/Layout/General.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/style.js
  client/src/constants/nav-routes.js
  client/src/pages/TestLanding/index.js
  client/src/pages/TestLanding/style.js
  client/src/pages/index.js
  client/src/theme/global-style.js
  client/src/theme/index.js
Labels: awaiting-review

#99 51 hq landing
  client/src/App.js
  client/src/constants/nav-routes.js
  client/src/pages/Landing/HQLanding.js
  client/src/pages/Landing/VolunteerLanding.js
  client/src/pages/index.js
Labels: awaiting-review

#101 67 hq volunteers stats
  client/src/App.js
  client/src/api-calls/index.js
  client/src/api-calls/volunteers.js
  client/src/components/Card/Card.stories.js
  client/src/components/Card/StatsCard/index.js
  client/src/components/Card/StatsCard/style.js
  client/src/components/Card/index.js
  client/src/components/index.js
  client/src/constants/nav-routes.js
  client/src/pages/HqVolunteersStats/index.js
  client/src/pages/HqVolunteersStats/style.js
  client/src/pages/index.js
  client/src/theme/index.js
  server/api/index.js
  server/database/dummy-data/users-completed-activities.js
  server/database/models/users-completed-activities/schema.sql
  server/database/models/users/schema.sql
  server/modules/index.js
  server/modules/volunteers/controllers/get-volunteers-stats.js
  server/modules/volunteers/controllers/index.js
  server/modules/volunteers/index.js
  server/modules/volunteers/model/create.js
  server/modules/volunteers/model/find.js
  server/modules/volunteers/model/index.js
  server/modules/volunteers/model/remove.js
  server/modules/volunteers/model/update.js
  server/modules/volunteers/use-cases/get-volunteers-stats.js
  server/modules/volunteers/use-cases/index.js
  server/modules/volunteers/utils/index.js
Labels: awaiting-review

#98 55 postcode page
  client/src/App.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Layout/Page.js
  client/src/components/Layout/style.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/find-postcode.js
  client/src/helpers/index.js
  client/src/helpers/tidy-postcode.js
  client/src/pages/Postcode/index.js
  client/src/pages/Postcode/style.js
  client/src/pages/index.js
  client/src/theme/index.js
  client/src/validation/err-msgs.js
Labels: awaiting-review

#97 37 create menu component
  .vscode/settings.json
  client/src/components/Icon/icons/Backup.js
  client/src/components/Icon/icons/BrokenLamp.js
  client/src/components/Icon/icons/Burger.js
  client/src/components/Icon/icons/Close.js
  client/src/components/Icon/icons/Crown.js
  client/src/components/Icon/icons/Discussion.js
  client/src/components/Icon/icons/File.js
  client/src/components/Icon/icons/Flash.js
  client/src/components/Icon/icons/Logo.js
  client/src/components/Icon/icons/Notebook.js
  client/src/components/Icon/icons/Office.js
  client/src/components/Icon/icons/Planning.js
  client/src/components/Icon/icons/Search.js
  client/src/components/Icon/index.js
  client/src/components/Layout/General.js
  client/src/components/Layout/Menu.js
  client/src/components/Layout/NavBar/index.js
  client/src/components/Layout/NavBar/style.js
  client/src/components/Layout/Page.js
  client/src/components/Layout/SideBar/index.js
  client/src/components/Layout/SideBar/style.js
  client/src/components/Layout/WithBlocks.js
  client/src/components/Layout/WithoutHeader.js
  client/src/components/Layout/index.js
  client/src/components/Menu/index.js
  client/src/components/Menu/style.js
  client/src/constants/nav-routes.js
  client/src/theme/index.js
Labels: awaiting-review

#100 80 Share Component
  client/package-lock.json
  client/package.json
  client/src/components/Share/Share.stories.js
  client/src/components/Share/index.js
  client/src/components/Share/style.js
Labels: requested-changes

#105 65 66 search page
  client/package-lock.json
  client/src/App.js
  client/src/api-calls/skills.js
  client/src/components/Card/Search/index.js
  client/src/components/Card/style.js
  client/src/components/Icon/icons/RightRow.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/Inputs.stories.js
  client/src/components/Layout/WithoutHeader.js
  client/src/components/Layout/style.js
  client/src/constants/nav-routes.js
  client/src/pages/Search/index.js
  client/src/pages/Search/style.js
  client/src/pages/index.js
  client/src/theme/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/login.js
  client/src/validation/schemas/search.js
  client/src/validation/schemas/signup.js
  package-lock.json
  package.json
  server/app.js
  server/database/dummy-data/activities.js
  server/database/dummy-data/skills.js
  server/database/models/activities/schema.sql
  server/database/models/skills/schema.sql
  server/modules/skills/controllers/get-skill-by-id.js
  server/modules/skills/controllers/get-skills-and-activities-popular.js
  server/modules/skills/controllers/get-skills-and-activities-search.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-skills-and-activities-popular.js
  server/modules/skills/use-cases/get-skills-and-activities-search.js
  server/modules/skills/use-cases/index.js
Labels: awaiting-review

#103 68 hq skills progress
  client/package-lock.json
  client/src/App.js
  client/src/api-calls/skills.js
  client/src/components/Card/StatsCard/style.js
  client/src/constants/nav-routes.js
  client/src/pages/HqSkillsProgress/index.js
  client/src/pages/index.js
  server/modules/skills/controllers/get-hq-skill-progress.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-hq-skill-progress.js
  server/modules/skills/use-cases/index.js
  server/modules/volunteers/use-cases/get-volunteers-stats.js
Labels: request changes

#107 102 Footer Component
  client/src/components/Footer/Footer.stories.js
  client/src/components/Footer/index.js
  client/src/components/Footer/style.js
  client/src/components/Layout/General.js
  client/src/components/Layout/WithBlocks.js
  client/src/components/Layout/WithoutHeader.js
  client/src/constants/nav-routes.js
  client/src/theme/index.js
Labels: requested-changes

#104 74 success add activity page
  client/src/App.js
  client/src/components/Icon/icons/Eye.js
  client/src/components/Icon/index.js
  client/src/components/ViewActivityLink/index.js
  client/src/components/ViewActivityLink/style.js
  client/src/constants/nav-routes.js
  client/src/pages/SuccessUpdateActivity/index.js
  client/src/pages/SuccessUpdateActivity/style.js
  client/src/pages/index.js
Labels: awaiting-review

#106 60 hq dashboard
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Loading/Loading.stories.js
  client/src/components/Loading/index.js
  client/src/components/Loading/style.js
  client/src/components/Typography/index.js
  client/src/components/index.js
  client/src/pages/HqDashboard/Card.js
  client/src/pages/HqDashboard/StatsMenuCard.js
  client/src/pages/HqDashboard/StatsMenuCard.style.js
  client/src/pages/HqDashboard/index.js
  client/src/pages/Login/index.js
  client/src/pages/index.js
  server/modules/users/controllers/get-user-dashboard.js
  server/modules/users/controllers/index.js
  server/modules/users/model/find.js
  server/modules/users/use-cases/get-user-dashboard.js
  server/modules/users/use-cases/index.js
Labels: awaiting-review

#109 69 i can view an overview of all skill areas hq front end
  client/src/App.js
  client/src/api-calls/index.js
  client/src/api-calls/skill-areas.js
  client/src/components/Card/SkillCard/index.js
  client/src/components/Card/SkillCard/style.js
  client/src/components/Card/index.js
  client/src/components/Grid/style.js
  client/src/components/Icon/icons/Burger.js
  client/src/components/Icon/icons/Clock.js
  client/src/components/Icon/icons/RightRow.js
  client/src/components/Menu/index.js
  client/src/constants/nav-routes.js
  client/src/pages/IndividualSkillArea/index.js
  client/src/pages/IndividualSkillArea/style.js
  client/src/pages/SkillAreas/index.js
  client/src/pages/SkillAreas/style.js
  client/src/pages/index.js
  client/src/theme/index.js
  server/api/index.js
  server/modules/index.js
  server/modules/skill-areas/controllers/get-hq-skill-areas.js
  server/modules/skill-areas/controllers/get-skill-area-by-id.js
  server/modules/skill-areas/controllers/index.js
  server/modules/skill-areas/index.js
  server/modules/skill-areas/model/create.js
  server/modules/skill-areas/model/find.js
  server/modules/skill-areas/model/index.js
  server/modules/skill-areas/model/remove.js
  server/modules/skill-areas/model/update.js
  server/modules/skill-areas/use-cases/get-hq-skill-areas.js
  server/modules/skill-areas/use-cases/get-skill-area-by-id.js
  server/modules/skill-areas/use-cases/index.js
  server/modules/skill-areas/utils/index.js
Labels: awaiting-review

#115 76 > Create Help Page
  client/src/App.js
  client/src/components/Card/Newsletter/index.js
  client/src/components/Card/Newsletter/style.js
  client/src/components/Layout/NavBar/style.js
  client/src/components/Layout/SideBar/index.js
  client/src/constants/nav-routes.js
  client/src/pages/HelpOthers/index.js
  client/src/pages/HelpOthers/style.js
  client/src/pages/Search/index.js
  client/src/pages/index.js
Labels: awaiting-review

#111 71 view individual skill
  client/src/App.js
  client/src/api-calls/activities.js
  client/src/components/Icon/icons/Edit.js
  client/src/components/Icon/index.js
  client/src/constants/nav-routes.js
  client/src/pages/HqIndividualSkill/index.js
  client/src/pages/HqIndividualSkill/style.js
  client/src/pages/index.js
  server/database/dummy-data/skills.js
  server/modules/activities/controllers/get-activities.js
  server/modules/activities/controllers/index.js
  server/modules/activities/model/find.js
  server/modules/activities/use-cases/get-activities-by-skill-id.js
  server/modules/activities/use-cases/index.js
  server/modules/skills/controllers/get-skill-by-id.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-skill-by-id.js
Labels: awaiting-review

#110 59 volunteers dashborad
  .vscode/settings.json
  client/src/App.js
  client/src/api-calls/skills.js
  client/src/components/Icon/icons/ArrowUp.js
  client/src/components/Icon/index.js
  client/src/components/Layout/style.js
  client/src/constants/nav-routes.js
  client/src/pages/Dashboard/Volunteer.js
  client/src/pages/Dashboard/style.js
  client/src/pages/Login/index.js
  client/src/pages/index.js
  server/modules/skills/controllers/get-skills-stats.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-skills-stats.js
  server/modules/skills/use-cases/index.js
Labels: awaiting-review

#114 61 recommended skills page fron end
  client/src/App.js
  client/src/components/Card/CTA/index.js
  client/src/components/Card/RecommendSkill/index.js
  client/src/components/Card/RecommendSkill/style.js
  client/src/components/Card/index.js
  client/src/components/Icon/icons/Trophy.js
  client/src/components/Icon/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/decide-color.js
  client/src/helpers/index.js
  client/src/pages/RecommendedSkills/dummyData.js
  client/src/pages/RecommendedSkills/index.js
  client/src/pages/RecommendedSkills/style.js
  client/src/pages/index.js
  client/src/theme/index.js
Labels: awaiting-review

#116 62 single skill volunteer
  client/src/App.js
  client/src/components/Card/ActivityCard/index.js
  client/src/components/Card/ActivityCard/style.js
  client/src/components/Card/CTA/index.js
  client/src/components/Card/Card.stories.js
  client/src/components/Card/index.js
  client/src/components/Icon/icons/ArrowDown.js
  client/src/components/Icon/icons/ArrowUp.js
  client/src/components/Icon/icons/CupWithFlash.js
  client/src/components/Icon/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/decide-color.js
  client/src/pages/HqIndividualSkill/style.js
  client/src/pages/VolunteerIndividualSkill/index.js
  client/src/pages/VolunteerIndividualSkill/style.js
  client/src/pages/index.js
  server/modules/activities/controllers/get-activities.js
  server/modules/activities/controllers/index.js
  server/modules/activities/model/find.js
  server/modules/activities/use-cases/get-activities-by-skill-id.js
  server/modules/skills/controllers/get-skill-by-id.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-skill-by-id.js
Labels: awaiting-review

#118 117 > Connect Test, Dashboard and Sign up
  client/src/App.js
  client/src/api-calls/skill-areas.js
  client/src/api-calls/users.js
  client/src/components/Inputs/Checkbox/index.js
  client/src/components/Inputs/Checkbox/style.js
  client/src/components/Menu/index.js
  client/src/constants/data-types.js
  client/src/constants/nav-routes.js
  client/src/helpers/assessmentStorage.js
  client/src/pages/Assessment/Questions/SkillAreaQ.js
  client/src/pages/Assessment/Questions/data.js
  client/src/pages/Assessment/index.js
  client/src/pages/Dashboard/Volunteer.js
  client/src/pages/Dashboard/style.js
  client/src/pages/IndividualSkillArea/index.js
  client/src/pages/Login/index.js
  client/src/pages/Signup/Volunteer.js
  client/src/pages/TestLanding/index.js
  client/src/validation/schemas/signup.js
  server/database/dummy-data/users-completed-activities.js
  server/modules/skill-areas/controllers/get-skill-areas.js
  server/modules/skill-areas/controllers/index.js
  server/modules/skill-areas/model/find.js
  server/modules/skill-areas/use-cases/get-skill-areas.js
  server/modules/skill-areas/use-cases/index.js
  server/modules/skills/model/find.js
  server/modules/users/controllers/signup.js
  server/modules/users/model/create.js
  server/modules/users/use-cases/volunteer-signup.js
Labels: awaiting-review

#120 recommended skills backend
  client/src/api-calls/skills.js
  client/src/components/Card/Card.stories.js
  client/src/components/Icon/icons/DefaultSkill.js
  client/src/components/Icon/index.js
  client/src/pages/Assessment/index.js
  client/src/pages/IndividualSkillArea/index.js
  client/src/pages/RecommendedSkills/dummyData.js
  client/src/pages/RecommendedSkills/index.js
  server/modules/skills/controllers/get-skills.js
  server/modules/skills/controllers/index.js
  server/modules/skills/model/find.js
  server/modules/skills/use-cases/get-skills.js
Labels: awaiting-review

#121 edit individual skill backend
  client/src/api-calls/skills.js
  client/src/components/SkillModal/index.js
  client/src/components/SkillModal/style.js
  client/src/components/index.js
  client/src/pages/HqIndividualSkill/index.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/schemas/update-skill.js
  server/modules/skills/controllers/index.js
  server/modules/skills/controllers/update-skill.js
  server/modules/skills/model/find.js
  server/modules/skills/model/update.js
  server/modules/skills/use-cases/index.js
  server/modules/skills/use-cases/update-skill.js
  server/modules/skills/utils/index.js
  server/modules/skills/utils/validate-edit-skill.js
  server/services/validation/err-msgs.js
  server/services/validation/fields.js
Labels: awaiting-review
